/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "graphe.h"

/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    creerGraphe
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterfaceAvecC_creerGraphe
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
